import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { gql } from '@apollo/client'
import { useMemo, useState } from 'react'
import { useConnection, useWallet } from '@solana/wallet-adapter-react'
import client from '../../client'

// import { NftCardHtml } from '../../components/NftCardHtml'
import { Navbar } from '../../components/Navbar'
import { useRouter } from 'next/router'

interface Nft { 
    name: string
    description: string
    files: any
    attributes: any
}

const GET_NFTS = gql`
  query GetNfts(
    $creators: [PublicKey!]
    $limit: Int!
    $offset: Int!
    $attributes: [AttributeFilter!]
  ) {
    nfts(
      creators: $creators
      limit: $limit
      offset: $offset
      attributes: $attributes
    ) {
      mintAddress
      name
      files {
        uri
      }
      owner {
        address
      }
    }
  }
`

export default function Profile () {
  const { publicKey, signTransaction, connected } = useWallet()
  const [nfts, setNfts] = useState<Nft[]>([])
  const router = useRouter()
  const { pubkey } = router.query

  useMemo(() => {
    if (pubkey) {
      client
        .query({
          query: GET_NFTS,
          variables: {
            creators: [pubkey],
            offset: 0,
            limit: 10000,
            attributes: { traitType: 'niftyplex', values: ['true'] }
          }
        })
        .then(res => setNfts(res.data.nfts))
    } else {
      setNfts([])
    }
  }, [pubkey])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />

        <main className={styles.main}>
            <div className='grid grid-cols-4 gap-4'>
            {nfts.map((nft, index) => {
              return <div key={Math.random()}><NftCardHtml name={nft.name} src={nft.files[0].uri} /></div>
            })}
                </div>
        </main>

    </div>
  )
}
