import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { gql } from '@apollo/client'
import { useMemo, useState } from 'react'
import { useConnection, useWallet } from '@solana/wallet-adapter-react'
import client from '../client'

// import { NftCardHtml } from '../components/NftCardHtml'
import { Navbar } from '../components/Navbar'

interface Nft {
  name: string
  description: string
  files: any
  attributes: any
}

const GET_NFTS = gql`
  query GetNfts(
    $creators: [PublicKey!]
    $limit: Int!
    $offset: Int!
    $attributes: [AttributeFilter!]
  ) {
    nfts(
      creators: $creators
      limit: $limit
      offset: $offset
      attributes: $attributes
    ) {
      mintAddress
      name
      files {
        uri
      }
      owner {
        address
      }
    }
  }
`

export default function Profile () {
  const { publicKey, signTransaction, connected } = useWallet()
  const [nfts, setNfts] = useState<Nft[]>([])

  useMemo(() => {
    if (publicKey?.toBase58()) {
      client
        .query({
          query: GET_NFTS,
          variables: {
            creators: [publicKey?.toBase58()],
            offset: 0,
            limit: 10000,
            attributes: { traitType: 'niftyplex', values: ['true'] }
          }
        })
        .then(res => {
          setNfts(res.data.nfts)
        })
    } else {
      setNfts([])
    }
  }, [publicKey])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      {!connected && <p>connect plz</p>}
      {connected && (
        <main className={styles.main}>
          {nfts.length > 0 ? (
            <div className='grid grid-cols-4 gap-4'>
              {nfts.map((nft, index) => {
                return (
                  <div key={Math.random()}>
                    {/* <NftCardHtml name={nft.name} src={nft.files[0].uri} /> */}
                  </div>
                )
              })}
            </div>
          ) : (
            <p>No nfts minted yet!</p>
          )}
        </main>
      )}
    </div>
  )
}
